[phases.setup]
nixPkgs = ["python311", "chromium", "chromedriver"]

[phases.build]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
